//! Build script: validates `environments.yaml` at compile time and generates
//! the list of valid environment names embedded into the binary.
//!
//! A malformed or empty `environments.yaml` fails the build, and the generated
//! `ENVIRONMENT_NAMES` constant lets the CLI validate `--environment` /
//! `--compare-with` against the names known at build time.

use serde::Deserialize;
use std::collections::BTreeMap;
use std::path::Path;
use std::{env, fs};

#[derive(Deserialize)]
struct BuildConfig {
    // BTreeMap keeps names sorted for deterministic, stable codegen.
    environments: BTreeMap<String, BTreeMap<String, String>>,
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo");
    let yaml_path = Path::new(&manifest_dir).join("../../environments.yaml");
    let example_path = Path::new(&manifest_dir).join("../../environments.example.yaml");

    println!("cargo:rerun-if-changed={}", yaml_path.display());
    println!("cargo:rerun-if-changed={}", example_path.display());

    // `environments.yaml` is gitignored (it holds real hosts/secret names), so
    // a fresh checkout — including CI — falls back to the committed example.
    let path = if yaml_path.exists() { &yaml_path } else { &example_path };

    let text = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));

    let config: BuildConfig =
        serde_yaml_ng::from_str(&text).unwrap_or_else(|e| panic!("invalid environments.yaml: {e}"));

    assert!(
        !config.environments.is_empty(),
        "environments.yaml must define at least one environment"
    );

    let names: Vec<String> = config
        .environments
        .keys()
        .map(|name| format!("{name:?}"))
        .collect();

    let generated = format!(
        "// @generated by build.rs from environments.yaml — do not edit.\n\
         /// Environment names defined in `environments.yaml`, embedded at build time.\n\
         pub const ENVIRONMENT_NAMES: &[&str] = &[{}];\n",
        names.join(", ")
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let dest = Path::new(&out_dir).join("environments_generated.rs");
    fs::write(&dest, generated).expect("failed to write generated environment names");

    // Copied verbatim (not just referenced) so `include_str!` in config.rs has
    // a stable, always-present path regardless of which source file was used.
    let resolved_dest = Path::new(&out_dir).join("environments_resolved.yaml");
    fs::write(&resolved_dest, &text).expect("failed to write resolved environments.yaml");
}
